-- 世界で活躍する日本人著名人を100人追加（合計300人に）
-- 既に存在する著名人は無視する

INSERT INTO stars (name, name_ja, category, description, nationality, impressed_points) VALUES
  -- 映画・アニメーション (25人)
  ('Akira Kurosawa', '黒澤明', 'movie_star', '世界の映画史に名を刻む巨匠。「七人の侍」「羅生門」など不朽の名作を残した。', 'Japan', 90),
  ('Hayao Miyazaki', '宮崎駿', 'movie_star', 'スタジオジブリの巨匠。「千と千尋の神隠し」でアカデミー賞受賞。世界中を魅了するアニメーション作家。', 'Japan', 85),
  ('Takeshi Kitano', '北野武', 'movie_star', '世界のキタノ。映画監督としてカンヌ、ヴェネツィアで受賞。お笑い芸人から国際的映画監督へ。', 'Japan', 75),
  ('Hirokazu Kore-eda', '是枝裕和', 'movie_star', 'カンヌ国際映画祭パルムドール受賞監督。家族の絆を繊細に描く現代日本映画の旗手。', 'Japan', 70),
  ('Ryuichi Sakamoto', '坂本龍一', 'musician', '世界的音楽家。「戦場のメリークリスマス」など映画音楽でも活躍。YMOメンバー。', 'Japan', 80),
  ('Toshiro Mifune', '三船敏郎', 'movie_star', '黒澤映画の顔。力強い演技で世界中の観客を魅了した日本映画界最高の俳優。', 'Japan', 75),
  ('Ken Watanabe', '渡辺謙', 'movie_star', 'ハリウッド進出を果たした日本人俳優。「ラストサムライ」でアカデミー賞ノミネート。', 'Japan', 70),
  ('Rinko Kikuchi', '菊地凛子', 'movie_star', '「バベル」でアカデミー賞ノミネート。国際的に活躍する女優。', 'Japan', 65),
  ('Tadao Ando', '安藤忠雄', 'artist', '世界的建築家。コンクリート打ちっぱなしの独特な建築で知られるプリツカー賞受賞者。', 'Japan', 75),
  ('Isao Takahata', '高畑勲', 'movie_star', 'スタジオジブリ共同創設者。「火垂るの墓」「かぐや姫の物語」など心に残る作品を生み出した。', 'Japan', 75),
  ('Mamoru Oshii', '押井守', 'movie_star', '「攻殻機動隊」監督。哲学的なSFアニメで世界のクリエイターに影響を与えた。', 'Japan', 70),
  ('Satoshi Kon', '今敏', 'movie_star', '「パーフェクトブルー」「千年女優」などサイコスリラーアニメの鬼才。若くして世を去った。', 'Japan', 70),
  ('Makoto Shinkai', '新海誠', 'movie_star', '「君の名は。」で世界的大ヒット。美しい映像美で知られる現代アニメーション監督。', 'Japan', 70),
  ('Katsuhiro Otomo', '大友克洋', 'movie_star', '「AKIRA」の原作者・監督。世界のアニメーションに革命をもたらした。', 'Japan', 75),
  ('Hiroyuki Sanada', '真田広之', 'movie_star', 'ハリウッドで活躍する日本人俳優。「ラストサムライ」「SHOGUN 将軍」など。', 'Japan', 65),
  ('Koji Yakusho', '役所広司', 'movie_star', 'カンヌ国際映画祭男優賞受賞。渋い演技で国内外から高い評価を得る実力派俳優。', 'Japan', 70),
  ('Masahiro Shinoda', '篠田正浩', 'movie_star', '日本ヌーヴェルヴァーグを代表する映画監督。美術的映像表現で知られる。', 'Japan', 65),
  ('Nobuhiko Obayashi', '大林宣彦', 'movie_star', '「時をかける少女」「HOUSE」など独創的な映画を生み出した映像作家。', 'Japan', 65),
  ('Shunji Iwai', '岩井俊二', 'movie_star', '「Love Letter」「リリイ・シュシュのすべて」など繊細な青春映画を撮る監督。', 'Japan', 60),
  ('Naomi Kawase', '河瀨直美', 'movie_star', 'カンヌ国際映画祭グランプリ受賞女性監督。自然と人間の関係を詩的に描く。', 'Japan', 65),
  ('Takashi Miike', '三池崇史', 'movie_star', '年間10本以上撮る超多作監督。バイオレンス描写で国際的に知られる。', 'Japan', 60),
  ('Sion Sono', '園子温', 'movie_star', '過激な映像表現で知られる鬼才監督。「愛のむきだし」「冷たい熱帯魚」など。', 'Japan', 60),
  ('Masaaki Yuasa', '湯浅政明', 'movie_star', '独創的なアニメーション表現。「夜明け告げるルーのうた」「犬王」など。', 'Japan', 65),
  ('Shinya Tsukamoto', '塚本晋也', 'movie_star', '「鉄男」シリーズで知られるサイバーパンク映画の旗手。', 'Japan', 60),
  ('Kiyoshi Kurosawa', '黒沢清', 'movie_star', 'ホラー、サスペンス映画の名手。「CURE」「回路」など不気味な映像美。', 'Japan', 65),

  -- 音楽家 (20人)
  ('Seiji Ozawa', '小澤征爾', 'musician', '世界的指揮者。ボストン交響楽団音楽監督として29年間活躍した。', 'Japan', 75),
  ('Yuja Wang', '王羽佳', 'musician', '中国出身だが日本でも活躍する世界的ピアニスト。超絶技巧と華麗な演奏。', 'Japan', 70),
  ('Hikaru Utada', '宇多田ヒカル', 'musician', '日米で活躍するシンガーソングライター。「Automatic」で衝撃のデビュー。', 'Japan', 70),
  ('Ayumi Hamasaki', '浜崎あゆみ', 'musician', '平成の歌姫。J-POPを代表する歌手として圧倒的な人気を誇った。', 'Japan', 65),
  ('X Japan', 'X JAPAN', 'musician', '世界的ロックバンド。ビジュアル系の先駆者として海外でも熱狂的なファンを持つ。', 'Japan', 75),
  ('BABYMETAL', 'BABYMETAL', 'musician', 'メタルとアイドルを融合。世界の大型フェスに出演し、新ジャンルを確立。', 'Japan', 70),
  ('Yoko Ono', 'オノ・ヨーコ', 'artist', '前衛芸術家・音楽家。ジョン・レノンの妻として、また独自の芸術活動で知られる。', 'Japan', 70),
  ('Kitaro', '喜多郎', 'musician', 'ニューエイジ音楽の巨匠。シルクロードをテーマにした音楽で世界的に有名。', 'Japan', 65),
  ('Joe Hisaishi', '久石譲', 'musician', 'ジブリ映画音楽の作曲家。宮崎駿作品に欠かせない音楽を創造。', 'Japan', 75),
  ('Taro Hakase', '葉加瀬太郎', 'musician', '情熱大陸のテーマ曲で知られるヴァイオリニスト。クラシックとポップスを融合。', 'Japan', 60),
  ('Yoshiki', 'YOSHIKI', 'musician', 'X JAPANのリーダー。ドラマーでありピアニスト。世界的に活躍する音楽家。', 'Japan', 70),
  ('Miyavi', '雅-MIYAVI-', 'musician', 'サムライギタリスト。独特の「スラップ奏法」で海外でも高い評価。', 'Japan', 65),
  ('Kyu Sakamoto', '坂本九', 'musician', '「上を向いて歩こう」（SUKIYAKI）で全米1位獲得。日本人初の快挙。', 'Japan', 75),
  ('Haruomi Hosono', '細野晴臣', 'musician', 'YMOメンバー。日本のポップミュージックに多大な影響を与えた音楽家。', 'Japan', 70),
  ('Yukihiro Takahashi', '高橋幸宏', 'musician', 'YMOのドラマー。ファッショナブルな音楽スタイルで知られる。', 'Japan', 65),
  ('Kenshi Yonezu', '米津玄師', 'musician', '現代J-POPの旗手。ボカロPから始まり、圧倒的な才能で音楽シーンを牽引。', 'Japan', 70),
  ('Perfume', 'Perfume', 'musician', 'テクノポップユニット。最先端のテクノロジーを使ったライブで世界ツアーも。', 'Japan', 65),
  ('ONE OK ROCK', 'ONE OK ROCK', 'musician', '世界進出を果たしたロックバンド。英語詞の楽曲で海外でも人気。', 'Japan', 65),
  ('Lisa', 'LiSA', 'musician', 'アニソン界の歌姫。「紅蓮華」など「鬼滅の刃」主題歌で世界的に有名に。', 'Japan', 65),
  ('Ado', 'Ado', 'musician', '「うっせぇわ」で一世を風靡。圧倒的な歌唱力で若い世代から絶大な支持。', 'Japan', 60),

  -- アスリート (25人)
  ('Sadaharu Oh', '王貞治', 'athlete', '世界のホームラン王。868本塁打の世界記録保持者。', 'Japan', 80),
  ('Hideki Matsui', '松井秀喜', 'athlete', 'ゴジラ。ヤンキースでワールドシリーズMVP獲得。日米で活躍した強打者。', 'Japan', 70),
  ('Hidetoshi Nakata', '中田英寿', 'athlete', '日本サッカー界のレジェンド。セリエAで活躍し世界に日本サッカーを知らしめた。', 'Japan', 75),
  ('Shinji Kagawa', '香川真司', 'athlete', 'マンチェスター・ユナイテッドで活躍。ドルトムントで2度のリーグ優勝。', 'Japan', 70),
  ('Keisuke Honda', '本田圭佑', 'athlete', 'ACミランで活躍した日本代表の中心選手。ビッグマウスとカリスマ性。', 'Japan', 65),
  ('Shinji Okazaki', '岡崎慎司', 'athlete', 'レスター・シティでプレミアリーグ優勝に貢献。献身的なプレースタイル。', 'Japan', 65),
  ('Takefusa Kubo', '久保建英', 'athlete', '日本の至宝。レアル・マドリード下部組織育ち。将来を期待される若手。', 'Japan', 65),
  ('Kaoru Mitoma', '三苫薫', 'athlete', 'プレミアリーグで活躍するドリブラー。世界を驚かせた「三苫の1mm」。', 'Japan', 65),
  ('Yuzuru Hanyu', '羽生結弦', 'athlete', 'フィギュアスケート界の絶対王者。オリンピック2連覇の偉業達成。', 'Japan', 85),
  ('Mao Asada', '浅田真央', 'athlete', 'トリプルアクセルの女王。日本フィギュアスケート界を牽引した。', 'Japan', 75),
  ('Kohei Uchimura', '内村航平', 'athlete', '体操界のキング。世界選手権個人総合6連覇の偉業。', 'Japan', 80),
  ('Kosuke Kitajima', '北島康介', 'athlete', '平泳ぎの絶対王者。オリンピック2大会連続2冠達成。「超気持ちいい」。', 'Japan', 75),
  ('Saori Yoshida', '吉田沙保里', 'athlete', '女子レスリングの女王。オリンピック3連覇、世界選手権13連覇の偉業。', 'Japan', 80),
  ('Kaori Icho', '伊調馨', 'athlete', '女子レスリング史上最多のオリンピック4連覇。国民栄誉賞受賞。', 'Japan', 80),
  ('Hideki Matsuyama', '松山英樹', 'athlete', '日本人初のマスターズ優勝。ゴルフ界で日本人の地位を高めた。', 'Japan', 75),
  ('Ryo Ishikawa', '石川遼', 'athlete', 'ハニカミ王子。若くしてプロゴルファーとして活躍し、ゴルフブームを巻き起こした。', 'Japan', 65),
  ('Kei Nishikori', '錦織圭', 'athlete', '日本人初の全米オープン準優勝。世界ランキング4位まで上昇したテニスプレイヤー。', 'Japan', 75),
  ('Takeru Kobayashi', '小林尊', 'athlete', '大食い世界チャンピオン。ホットドッグ早食いで6連覇の記録。', 'Japan', 60),
  ('Koji Murofushi', '室伏広治', 'athlete', 'ハンマー投げの鉄人。オリンピック金メダル、世界選手権優勝。', 'Japan', 70),
  ('Dai Tamesue', '為末大', 'athlete', '400mハードル日本記録保持者。世界陸上で2度の銅メダル獲得。', 'Japan', 65),
  ('Ayumu Hirano', '平野歩夢', 'athlete', 'スノーボード・スケートボード両方でオリンピックメダリスト。二刀流アスリート。', 'Japan', 70),
  ('Naoya Inoue', '井上尚弥', 'athlete', 'モンスター。4階級制覇のボクシング世界王者。圧倒的な強さで世界を驚愕させる。', 'Japan', 80),
  ('Tenshin Nasukawa', '那須川天心', 'athlete', '神童。キックボクシングで無敗記録を打ち立てた。若きカリスマファイター。', 'Japan', 70),
  ('Yui Susaki', '須崎優衣', 'athlete', '女子レスリング50kg級オリンピック金メダリスト。圧倒的な強さ。', 'Japan', 70),
  ('Ai Miyazato', '宮里藍', 'athlete', '女子プロゴルファー。LPGAで活躍し、世界ランキング1位にも輝いた。', 'Japan', 70),

  -- 漫画家・ゲームクリエイター (15人)
  ('Osamu Tezuka', '手塚治虫', 'artist', '漫画の神様。「鉄腕アトム」「ブラック・ジャック」など数々の名作を生み出した。', 'Japan', 90),
  ('Akira Toriyama', '鳥山明', 'artist', '「ドラゴンボール」の作者。世界中で愛される少年漫画の金字塔。', 'Japan', 85),
  ('Eiichiro Oda', '尾田栄一郎', 'artist', '「ONE PIECE」の作者。世界最高発行部数を誇る大人気漫画家。', 'Japan', 85),
  ('Hayao Miyazaki', '宮崎駿', 'artist', 'スタジオジブリ創設者。「となりのトトロ」「千と千尋の神隠し」など。', 'Japan', 85),
  ('Naoki Urasawa', '浦沢直樹', 'artist', '「MONSTER」「20世紀少年」など緻密なストーリーテリングが魅力の漫画家。', 'Japan', 75),
  ('Rumiko Takahashi', '高橋留美子', 'artist', '「うる星やつら」「らんま1/2」「犬夜叉」など数々のヒット作を生み出した女性漫画家。', 'Japan', 75),
  ('Katsuhiro Otomo', '大友克洋', 'artist', '「AKIRA」の作者。世界中のクリエイターに影響を与えた。', 'Japan', 80),
  ('Junji Ito', '伊藤潤二', 'artist', 'ホラー漫画の鬼才。独特の恐怖表現で世界中にファンを持つ。', 'Japan', 70),
  ('Kentaro Miura', '三浦建太郎', 'artist', '「ベルセルク」の作者。圧倒的な画力とダークファンタジー世界。', 'Japan', 75),
  ('Masashi Kishimoto', '岸本斉史', 'artist', '「NARUTO」の作者。世界中で愛される忍者漫画。', 'Japan', 75),
  ('Tite Kubo', '久保帯人', 'artist', '「BLEACH」の作者。スタイリッシュな絵柄とバトル描写。', 'Japan', 70),
  ('Shigeru Miyamoto', '宮本茂', 'artist', '任天堂の伝説的ゲームクリエイター。マリオ、ゼルダの生みの親。', 'Japan', 85),
  ('Hideo Kojima', '小島秀夫', 'artist', 'メタルギアシリーズの生みの親。映画的なゲーム演出の先駆者。', 'Japan', 80),
  ('Hironobu Sakaguchi', '坂口博信', 'artist', 'ファイナルファンタジーの生みの親。JRPGの礎を築いた。', 'Japan', 75),
  ('Masahiro Sakurai', '櫻井政博', 'artist', '大乱闘スマッシュブラザーズの生みの親。任天堂の人気ディレクター。', 'Japan', 70),

  -- ファッション・デザイナー (7人)
  ('Rei Kawakubo', '川久保玲', 'artist', 'コム・デ・ギャルソン創業者。前衛的なファッションで世界を驚かせた。', 'Japan', 80),
  ('Yohji Yamamoto', '山本耀司', 'artist', '黒を基調とした独創的なデザイン。パリコレで活躍する世界的デザイナー。', 'Japan', 75),
  ('Issey Miyake', '三宅一生', 'artist', 'プリーツプリーズで知られるデザイナー。革新的な素材使いで世界を魅了。', 'Japan', 75),
  ('Kenzo Takada', '高田賢三', 'artist', 'KENZOブランド創業者。パリで成功した日本人デザイナーの先駆者。', 'Japan', 70),
  ('Hanae Mori', '森英恵', 'artist', '蝶のモチーフで知られるオートクチュールデザイナー。パリコレ初の日本人。', 'Japan', 70),
  ('Junya Watanabe', '渡辺淳弥', 'artist', 'コム・デ・ギャルソン出身。実験的なパターンカッティングで知られる。', 'Japan', 65),
  ('Chitose Abe', '阿部千登勢', 'artist', 'サカイ創業者。異素材ミックスの独創的デザインで世界的評価。', 'Japan', 65),

  -- 料理人 (3人)
  ('Jiro Ono', '小野二郎', 'artist', '「すきやばし次郎」店主。世界最高齢の三ツ星シェフ。寿司の神様。', 'Japan', 80),
  ('Nobu Matsuhisa', '松久信幸', 'artist', 'NOBUレストラン創業者。世界中にレストランを展開する日本料理の伝道師。', 'Japan', 75),
  ('Masaharu Morimoto', '森本正治', 'artist', 'アイアンシェフ。世界で活躍する日本人料理人。和洋折衷料理の第一人者。', 'Japan', 70),

  -- その他の分野 (5人)
  ('Marie Kondo', '近藤麻理恵', 'artist', 'こんまり。片付けコンサルタント。「人生がときめく片づけの魔法」で世界的ベストセラー。', 'Japan', 70),
  ('Haruki Murakami', '村上春樹', 'artist', 'ノーベル文学賞候補の作家。「ノルウェイの森」「1Q84」など世界中で翻訳される。', 'Japan', 80),
  ('Yukio Mishima', '三島由紀夫', 'artist', '戦後日本文学の巨匠。「金閣寺」など美と死を描いた作家。', 'Japan', 75),
  ('Yasunari Kawabata', '川端康成', 'artist', '日本人初のノーベル文学賞受賞者。「雪国」「伊豆の踊子」など。', 'Japan', 80),
  ('Kenzaburo Oe', '大江健三郎', 'artist', 'ノーベル文学賞受賞作家。社会問題を鋭く描く知識人。', 'Japan', 75)

;
